// English to Urdu translation dictionary
const translationDict: Record<string, string> = {
  // Articles and basic words
  the: "یہ",
  a: "ایک",
  an: "ایک",
  and: "اور",
  or: "یا",
  but: "لیکن",
  if: "اگر",
  then: "پھر",
  else: "ورنہ",
  when: "کب",
  where: "کہاں",
  why: "کیوں",
  how: "کیسے",
  what: "کیا",
  who: "کون",
  which: "کون سا",

  // Pronouns
  i: "میں",
  you: "آپ",
  he: "وہ",
  she: "وہ",
  it: "یہ",
  we: "ہم",
  they: "وہ",
  this: "یہ",
  that: "وہ",
  these: "یہ",
  those: "وہ",
  my: "میرا",
  your: "آپ کا",
  his: "اس کا",
  her: "اس کا",
  its: "اس کا",
  our: "ہمارا",
  their: "ان کا",

  // Common verbs
  is: "ہے",
  are: "ہیں",
  am: "ہوں",
  was: "تھا",
  were: "تھے",
  will: "گا",
  would: "گا",
  can: "سکتا",
  could: "سکتا تھا",
  should: "چاہیے",
  may: "ہو سکتا",
  might: "ہو سکتا",
  must: "ضروری",
  shall: "گا",
  be: "ہونا",
  have: "رکھنا",
  has: "رکھتا ہے",
  had: "رکھتا تھا",
  do: "کرنا",
  does: "کرتا ہے",
  did: "کیا",
  go: "جانا",
  come: "آنا",
  see: "دیکھنا",
  know: "جاننا",
  think: "سوچنا",
  take: "لینا",
  get: "حاصل کرنا",
  make: "بنانا",
  give: "دینا",
  use: "استعمال کرنا",
  find: "تلاش کرنا",
  tell: "بتانا",
  ask: "پوچھنا",
  try: "کوشش کرنا",
  need: "ضرورت ہونا",
  want: "چاہنا",
  help: "مدد کرنا",
  show: "دکھانا",
  play: "کھیلنا",
  move: "حرکت کرنا",
  live: "رہنا",
  believe: "یقین کرنا",
  bring: "لانا",
  happen: "ہونا",
  write: "لکھنا",
  read: "پڑھنا",
  speak: "بولنا",
  listen: "سننا",
  look: "دیکھنا",
  watch: "دیکھنا",
  hear: "سننا",
  feel: "محسوس کرنا",
  eat: "کھانا",
  drink: "پینا",
  sleep: "سونا",
  wake: "جاگنا",
  walk: "چلنا",
  run: "دوڑنا",
  sit: "بیٹھنا",
  stand: "کھڑا ہونا",
  open: "کھولنا",
  close: "بند کرنا",
  start: "شروع کرنا",
  stop: "رکنا",
  work: "کام کرنا",
  study: "پڑھنا",
  learn: "سیکھنا",
  teach: "سکھانا",
  understand: "سمجھنا",
  remember: "یاد رکھنا",
  forget: "بھولنا",
  love: "محبت کرنا",
  like: "پسند کرنا",
  buy: "خریدنا",
  sell: "بیچنا",
  pay: "ادا کرنا",
  spend: "خرچ کرنا",
  save: "بچانا",
  earn: "کمانا",

  // Common nouns
  time: "وقت",
  person: "شخص",
  people: "لوگ",
  man: "آدمی",
  woman: "عورت",
  child: "بچہ",
  children: "بچے",
  boy: "لڑکا",
  girl: "لڑکی",
  family: "خاندان",
  friend: "دوست",
  house: "گھر",
  home: "گھر",
  school: "اسکول",
  job: "نوکری",
  money: "پیسہ",
  food: "کھانا",
  water: "پانی",
  book: "کتاب",
  car: "گاڑی",
  day: "دن",
  night: "رات",
  morning: "صبح",
  evening: "شام",
  year: "سال",
  month: "مہینہ",
  week: "ہفتہ",
  hour: "گھنٹہ",
  minute: "منٹ",
  world: "دنیا",
  country: "ملک",
  city: "شہر",
  place: "جگہ",
  way: "راستہ",
  life: "زندگی",
  hand: "ہاتھ",
  eye: "آنکھ",
  head: "سر",
  body: "جسم",
  heart: "دل",
  health: "صحت",
  problem: "مسئلہ",
  question: "سوال",
  answer: "جواب",
  idea: "خیال",
  story: "کہانی",
  news: "خبر",
  information: "معلومات",
  system: "نظام",
  service: "خدمت",
  business: "کاروبار",
  company: "کمپنی",
  government: "حکومت",
  education: "تعلیم",
  technology: "ٹیکنالوجی",
  computer: "کمپیوٹر",
  internet: "انٹرنیٹ",

  // Adjectives
  new: "نیا",
  old: "پرانا",
  young: "جوان",
  big: "بڑا",
  small: "چھوٹا",
  large: "بڑا",
  little: "چھوٹا",
  long: "لمبا",
  short: "چھوٹا",
  high: "اونچا",
  low: "نیچا",
  good: "اچھا",
  bad: "برا",
  great: "عظیم",
  best: "بہترین",
  better: "بہتر",
  worse: "بدتر",
  worst: "بدترین",
  right: "صحیح",
  wrong: "غلط",
  true: "سچا",
  false: "جھوٹا",
  real: "حقیقی",
  important: "اہم",
  different: "مختلف",
  same: "ویسا ہی",
  easy: "آسان",
  hard: "مشکل",
  difficult: "مشکل",
  simple: "آسان",
  free: "آزاد",
  closed: "بند",
  full: "بھرا",
  empty: "خالی",
  clean: "صاف",
  dirty: "گندا",
  hot: "گرم",
  cold: "ٹھنڈا",
  warm: "گرم",
  cool: "ٹھنڈا",
  fast: "تیز",
  slow: "آہستہ",
  quick: "جلدی",
  strong: "مضبوط",
  weak: "کمزور",
  heavy: "بھاری",
  light: "ہلکا",
  dark: "اندھیرا",
  bright: "روشن",
  beautiful: "خوبصورت",
  ugly: "بدصورت",
  nice: "اچھا",
  happy: "خوش",
  sad: "اداس",
  angry: "غصہ",
  tired: "تھکا ہوا",
  hungry: "بھوکا",
  sick: "بیمار",
  healthy: "صحت مند",
  rich: "امیر",
  poor: "غریب",
  smart: "ہوشیار",
  stupid: "بیوقوف",
  kind: "مہربان",
  mean: "بدمعاش",
  safe: "محفوظ",
  dangerous: "خطرناک",
  expensive: "مہنگا",
  cheap: "سستا",
  popular: "مقبول",
  famous: "مشہور",
  special: "خاص",
  normal: "عام",
  possible: "ممکن",
  impossible: "ناممکن",
  necessary: "ضروری",
  useful: "مفید",
  interesting: "دلچسپ",
  boring: "بورنگ",
  amazing: "حیرت انگیز",
  wonderful: "شاندار",
  excellent: "بہترین",
  perfect: "کامل",

  // Time and frequency
  today: "آج",
  yesterday: "کل",
  tomorrow: "کل",
  now: "اب",
  before: "پہلے",
  after: "بعد میں",
  always: "ہمیشہ",
  never: "کبھی نہیں",
  sometimes: "کبھی کبھی",
  often: "اکثر",
  usually: "عام طور پر",
  rarely: "شاذ و نادر",
  again: "دوبارہ",
  once: "ایک بار",
  twice: "دو بار",
  first: "پہلا",
  last: "آخری",
  next: "اگلا",
  early: "جلدی",
  late: "دیر",

  // Numbers
  one: "ایک",
  two: "دو",
  three: "تین",
  four: "چار",
  five: "پانچ",
  six: "چھ",
  seven: "سات",
  eight: "آٹھ",
  nine: "نو",
  ten: "دس",
  hundred: "سو",
  thousand: "ہزار",
  million: "لاکھ",

  // Colors
  red: "سرخ",
  blue: "نیلا",
  green: "سبز",
  yellow: "پیلا",
  black: "کالا",
  white: "سفید",
  brown: "بھورا",
  orange: "نارنجی",
  purple: "جامنی",
  pink: "گلابی",

  // Directions and positions
  here: "یہاں",
  there: "وہاں",
  up: "اوپر",
  down: "نیچے",
  left: "بائیں",
  front: "سامنے",
  back: "پیچھے",
  inside: "اندر",
  outside: "باہر",
  near: "قریب",
  far: "دور",
  above: "اوپر",
  below: "نیچے",
  between: "درمیان",
  among: "میں سے",
  around: "ارد گرد",

  // Common phrases and connectors
  yes: "ہاں",
  no: "نہیں",
  please: "براہ کرم",
  thank: "شکریہ",
  sorry: "معذرت",
  hello: "سلام",
  goodbye: "الوداع",
  welcome: "خوش آمدید",
  because: "کیونکہ",
  so: "اس لیے",
  also: "بھی",
  too: "بھی",
  very: "بہت",
  much: "بہت",
  many: "بہت",
  more: "زیادہ",
  less: "کم",
  most: "سب سے زیادہ",
  some: "کچھ",
  all: "سب",
  every: "ہر",
  each: "ہر ایک",
  both: "دونوں",
  only: "صرف",
  just: "صرف",
  about: "کے بارے میں",
  with: "کے ساتھ",
  without: "کے بغیر",
  for: "کے لیے",
  from: "سے",
  to: "کو",
  in: "میں",
  on: "پر",
  at: "پر",
  by: "کے ذریعے",
  of: "کا",
  as: "جیسا",
  than: "سے",
  into: "میں",
  out: "باہر",
  over: "اوپر",
  under: "نیچے",
  through: "کے ذریعے",
  during: "دوران",
  until: "جب تک",
  since: "جب سے",
  while: "جبکہ",
}

export function translateToUrdu(text: string): string {
  // Split text into words and translate each word
  const words = text.toLowerCase().split(/\s+/)

  const translatedWords = words.map((word) => {
    // Remove punctuation for lookup
    const cleanWord = word.replace(/[^\w]/g, "")

    // Look up translation
    const translation = translationDict[cleanWord]

    if (translation) {
      // Preserve original punctuation
      const punctuation = word.replace(/\w/g, "")
      return translation + punctuation
    }

    // If no translation found, keep original word
    return word
  })

  return translatedWords.join(" ")
}
